# Generated by Django 5.1 on 2026-03-05 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RevenueForecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("forecast_month", models.DateField()),
                (
                    "predicted_amount",
                    models.DecimalField(decimal_places=0, max_digits=15),
                ),
                ("confidence_score", models.FloatField(default=0.0)),
                (
                    "lower_bound",
                    models.DecimalField(decimal_places=0, default=0, max_digits=15),
                ),
                (
                    "upper_bound",
                    models.DecimalField(decimal_places=0, default=0, max_digits=15),
                ),
                ("insights", models.JSONField(default=dict)),
                ("model_version", models.CharField(default="v1", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revenue_forecasts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-forecast_month"],
                "unique_together": {("user", "forecast_month")},
            },
        ),
    ]
