# Generated by Django 5.1 on 2026-03-04 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PortfolioItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, max_length=500)),
                ("image_url", models.URLField()),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("logo", "Desain Logo"),
                            ("branding", "Branding & Identity"),
                            ("social_media", "Desain Social Media"),
                            ("illustration", "Ilustrasi"),
                            ("photo_product", "Foto Produk"),
                            ("photo_event", "Foto Event"),
                            ("video_promo", "Video Promosi"),
                            ("video_event", "Video Event"),
                            ("copywriting", "Copywriting"),
                            ("translation", "Penerjemahan"),
                            ("music", "Produksi Musik"),
                            ("web_dev", "Web Development"),
                            ("other", "Lainnya"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, max_length=1000)),
                ("base_price", models.DecimalField(decimal_places=0, max_digits=12)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("logo", "Desain Logo"),
                            ("branding", "Branding & Identity"),
                            ("social_media", "Desain Social Media"),
                            ("illustration", "Ilustrasi"),
                            ("photo_product", "Foto Produk"),
                            ("photo_event", "Foto Event"),
                            ("video_promo", "Video Promosi"),
                            ("video_event", "Video Event"),
                            ("copywriting", "Copywriting"),
                            ("translation", "Penerjemahan"),
                            ("music", "Produksi Musik"),
                            ("web_dev", "Web Development"),
                            ("other", "Lainnya"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
