# Generated by Django 5.1 on 2026-03-04 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="banner_url",
            field=models.URLField(blank=True),
        ),
    ]
