# Generated by Django 5.1 on 2026-03-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_banner_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="invoice_accent_color",
            field=models.CharField(blank=True, default="", max_length=7),
        ),
        migrations.AddField(
            model_name="user",
            name="invoice_logo_url",
            field=models.URLField(blank=True),
        ),
    ]
