# Generated by Django 5.1 on 2026-03-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_invoice_accent_color_user_invoice_logo_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="average_project_value",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="user",
            name="experience_years",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="last_forecast_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="last_revenue_forecast",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="total_projects_completed",
            field=models.IntegerField(default=0),
        ),
    ]
