# Generated by Django 5.1 on 2026-03-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_pricing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketPricing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_category", models.CharField(max_length=20)),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("junior", "0-2 tahun"),
                            ("mid", "2-5 tahun"),
                            ("senior", "5+ tahun"),
                        ],
                        max_length=20,
                    ),
                ),
                ("min_price", models.DecimalField(decimal_places=0, max_digits=12)),
                ("optimal_price", models.DecimalField(decimal_places=0, max_digits=12)),
                ("max_price", models.DecimalField(decimal_places=0, max_digits=12)),
                ("sample_size", models.IntegerField(default=0)),
                ("market_demand", models.FloatField(default=1.0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-last_updated"],
                "unique_together": {("service_category", "experience_level")},
            },
        ),
    ]
