# Generated by Django 5.1 on 2026-03-04 05:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(blank=True, max_length=20, unique=True),
                ),
                ("client_name", models.CharField(max_length=200)),
                ("client_email", models.EmailField(blank=True, max_length=254)),
                ("client_phone", models.CharField(blank=True, max_length=20)),
                ("items", models.JSONField(default=list)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=0, default=0, max_digits=15),
                ),
                (
                    "tax_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=0, default=0, max_digits=15),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=0, default=0, max_digits=15),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Terkirim"),
                            ("paid", "Dibayar"),
                            ("cancelled", "Dibatalkan"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("payment_method", models.CharField(blank=True, max_length=20)),
                ("midtrans_order_id", models.CharField(blank=True, max_length=100)),
                ("midtrans_snap_token", models.CharField(blank=True, max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=12, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
