# Generated by Django 5.1 on 2026-03-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="currency",
            field=models.CharField(
                choices=[
                    ("IDR", "Rupiah (IDR)"),
                    ("USD", "US Dollar (USD)"),
                    ("SGD", "Singapore Dollar (SGD)"),
                    ("EUR", "Euro (EUR)"),
                    ("MYR", "Malaysian Ringgit (MYR)"),
                ],
                default="IDR",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="last_reminded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
