# Generated by Django 5.1 on 2026-03-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0003_invoice_currency_invoice_last_reminded_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="client_risk_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="payment_delay_days",
            field=models.IntegerField(default=0),
        ),
    ]
